In [1]:
%pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

Data Loading

In [3]:
from google.colab import files
uploaded = files.upload()

Saving amazon_products_sales_data_cleaned (2).csv to amazon_products_sales_data_cleaned (2).csv

Data Overview

In [5]:
df = pd.read_csv('amazon_products_sales_data_cleaned (2).csv')
df.head()

,product_title,product_rating,total_reviews,purchased_last_month,discounted_price,original_price,is_best_seller,is_sponsored,has_coupon,buy_box_availability,delivery_date,sustainability_tags,product_image_url,product_page_url,data_collected_at,product_category,discount_percentage
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375.0,300.0,89.68,159.00,No Badge,Sponsored,Save 15% with coupon,Add to cart,2025-09-01,Carbon impact,https://m.media-amazon.com/images/I/71pAqiVEs3...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Phones,43.60
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3,2457.0,6000.0,9.99,15.99,No Badge,Sponsored,No Coupon,Add to cart,2025-08-29,NaN,https://m.media-amazon.com/images/I/61nbF6aVIP...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Laptops,37.52
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6,3044.0,2000.0,314.00,349.00,No Badge,Sponsored,No Coupon,Add to cart,2025-09-01,NaN,https://m.media-amazon.com/images/I/61h78MEXoj...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Laptops,10.03
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6,35882.0,10000.0,162.24,162.24,Best Seller,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61SUj2aKoE...,https://www.amazon.com/Apple-Cancellation-Tran...,2025-08-21 11:14:29,Phones,0.00
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8,28988.0,10000.0,72.74,72.74,No Badge,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61bMNCeAUA...,https://www.amazon.com/Apple-MX542LL-A-AirTag-...,2025-08-21 11:14:29,Phones,0.00

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42675 entries, 0 to 42674
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   product_title         42675 non-null  object
 1   product_rating        41651 non-null  float64
 2   total_reviews         41651 non-null  float64
 3   purchased_last_month  32164 non-null  float64
 4   discounted_price      40613 non-null  float64
 5   original_price        40613 non-null  float64
 6   is_best_seller        42675 non-null  object
 7   is_sponsored          42675 non-null  object
 8   has_coupon            42675 non-null  object
 9   buy_box_availability  28022 non-null  object
 10  delivery_date         30692 non-null  object
 11  sustainability_tags   3408 non-null   object
 12  product_image_url     42675 non-null  object
 13  product_page_url      40606 non-null  object
 14  data_collected_at     42675 non-null  object
 15  product_category      42675 non-null  object
 16  discount_percentage   40613 non-null  float64
dtypes: float64(6), object(11)
memory usage: 5.5+ MB

Data Cleaning

In [8]:
df.duplicated().sum()

np.int64(0)

In [43]:
df.isnull().sum()

product_rating          0
total_reviews           0
purchased_last_month    0
discounted_price        0
original_price          0
discount_percentage     0
product_title           0
is_best_seller          0
is_sponsored            0
has_coupon              0
buy_box_availability    0
delivery_date           0
product_image_url       0
product_page_url        0
data_collected_at       0
product_category        0
dtype: int64

In [10]:
df.describe()

,product_rating,total_reviews,purchased_last_month,discounted_price,original_price,discount_percentage
count,41651.000000,41651.000000,32164.000000,40613.000000,40613.000000,40613.000000
mean,4.399431,3087.106000,1293.665278,243.227289,257.611107,6.547151
std,0.386997,13030.460133,6318.323574,473.351545,496.633495,12.744715
min,1.000000,1.000000,50.000000,2.160000,2.160000,0.000000
25%,4.200000,82.000000,100.000000,29.690000,32.990000,0.000000
50%,4.500000,343.000000,200.000000,84.990000,89.000000,0.000000
75%,4.700000,1886.000000,400.000000,224.000000,229.990000,8.490000
max,5.000000,865598.000000,100000.000000,5449.000000,5449.000000,85.420000

In [40]:
for col in df.select_dtypes(include='number').columns:
    df[col].fillna(df[col].median(), inplace=True)

for col in df.select_dtypes(exclude='number').columns:
    df[col].fillna(df[col].mode()[0], inplace=True)

/tmp/ipykernel_30712/3898462176.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
/tmp/ipykernel_30712/3898462176.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)
/tmp/ipykernel_30712/3898462176.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)
/tmp/ipykernel_30712/3898462176.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

In [41]:
df.head()

,product_rating,total_reviews,purchased_last_month,discounted_price,original_price,discount_percentage,product_title,is_best_seller,is_sponsored,has_coupon,buy_box_availability,delivery_date,product_image_url,product_page_url,data_collected_at,product_category
0,4.6,375,300,89.68,159.00,43.60,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,No Badge,Sponsored,Save 15% with coupon,Add to cart,2025-09-01,https://m.media-amazon.com/images/I/71pAqiVEs3...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Phones
1,4.3,2457,6000,9.99,15.99,37.52,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",No Badge,Sponsored,No Coupon,Add to cart,2025-08-29,https://m.media-amazon.com/images/I/61nbF6aVIP...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Laptops
2,4.6,3044,2000,314.00,349.00,10.03,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",No Badge,Sponsored,No Coupon,Add to cart,2025-09-01,https://m.media-amazon.com/images/I/61h78MEXoj...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Laptops
3,4.6,35882,10000,162.24,162.24,0.00,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",Best Seller,Organic,No Coupon,Add to cart,2025-09-04,https://m.media-amazon.com/images/I/61SUj2aKoE...,https://www.amazon.com/Apple-Cancellation-Tran...,2025-08-21 11:14:29,Phones
4,4.8,28988,10000,72.74,72.74,0.00,Apple AirTag 4 Pack. Keep Track of and find Yo...,No Badge,Organic,No Coupon,Add to cart,2025-09-04,https://m.media-amazon.com/images/I/61bMNCeAUA...,https://www.amazon.com/Apple-MX542LL-A-AirTag-...,2025-08-21 11:14:29,Phones

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42675 entries, 0 to 42674
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   product_rating        42675 non-null  float64
 1   total_reviews         42675 non-null  int64
 2   purchased_last_month  42675 non-null  int64
 3   discounted_price      42675 non-null  float64
 4   original_price        42675 non-null  float64
 5   discount_percentage   42675 non-null  float64
 6   product_title         42675 non-null  object
 7   is_best_seller        42675 non-null  object
 8   is_sponsored          42675 non-null  object
 9   has_coupon            42675 non-null  object
 10  buy_box_availability  42675 non-null  object
 11  delivery_date         42675 non-null  datetime64[ns]
 12  product_image_url     42675 non-null  object
 13  product_page_url      42675 non-null  object
 14  data_collected_at     42675 non-null  datetime64[ns]
 15  product_category      42675 non-null  object
dtypes: datetime64[ns](2), float64(4), int64(2), object(8)
memory usage: 5.2+ MB

In [24]:
df['total_reviews'] = df['total_reviews'].astype(int)

In [25]:
df['purchased_last_month'] = df['purchased_last_month'].astype(int)

In [26]:
df['delivery_date'] = pd.to_datetime(df['delivery_date'], errors = 'coerce')
df['data_collected_at'] = pd.to_datetime(df['data_collected_at'], errors = 'coerce')

In [28]:
df.drop(['sustainability_tags'],axis = 1, inplace = True)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42675 entries, 0 to 42674
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   product_rating        42675 non-null  float64
 1   total_reviews         42675 non-null  int64
 2   purchased_last_month  42675 non-null  int64
 3   discounted_price      42675 non-null  float64
 4   original_price        42675 non-null  float64
 5   discount_percentage   42675 non-null  float64
 6   product_title         42675 non-null  object
 7   is_best_seller        42675 non-null  object
 8   is_sponsored          42675 non-null  object
 9   has_coupon            42675 non-null  object
 10  buy_box_availability  42675 non-null  object
 11  delivery_date         42675 non-null  datetime64[ns]
 12  product_image_url     42675 non-null  object
 13  product_page_url      42675 non-null  object
 14  data_collected_at     42675 non-null  datetime64[ns]
 15  product_category      42675 non-null  object
dtypes: datetime64[ns](2), float64(4), int64(2), object(8)
memory usage: 5.2+ MB

Data Analysis

In [31]:
df.groupby('is_sponsored')['purchased_last_month'].mean()

is_sponsored
Organic       430.542003
Sponsored    4044.615604
Name: purchased_last_month, dtype: float64

In [33]:
df.groupby('product_category')['purchased_last_month'].sum().sort_values(ascending=False)

product_category
Power & Batteries      26170250
Other Electronics       4091800
Phones                  3880950
Laptops                 3828250
Cameras                 1050900
TV & Display             967150
Chargers & Cables        879550
Wearables                786850
Storage                  628050
Networking               321850
Speakers                 301950
Printers & Scanners      290450
Headphones               230350
Gaming                   152100
Smart Home               131200
Name: purchased_last_month, dtype: int64

Key Insights
1. Sponsored vs Organic Products

Sponsored products show significantly higher average purchases than organic products.
Indicates that paid promotions improve visibility and sales performance.

2. Category Performance
Power & Batteries accounts for 26.17M purchases, representing ~60–65% of total demand
Significantly outperforms all other categories.